title: NCHS Computer Science
description: Intermediated Data Programming (IDP) & Advanced Topics (Java)
theme: just-the-docs
favicon_ico: "/assets/images/favicon.ico"
url: https://nchs-cs.github.io/
logo: "/assets/images/Jaguar_Logo_Small.png"

exclude:
  - external/

aux_links:
  Site GitHub: https://github.com/NCHS-CS/nchs-cs.github.io

nav_external_links:
  - title: LearnGitBranching
    url: https://nchs-cs.github.io/idp/static/gitbranching/learnGitBranching
    opens_in_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  # Docs: https://www.jsdelivr.com/package/npm/mermaid 
  version: "11.5.0"

callouts:
  notice:
    title: Notice
    color: blue
  warning:
    title: Warning
    color: yellow
  alert:
    title: Alert
    color: red
  example:
    title: Example
    color: green

enable_copy_code_button: true

plugins:
  - jekyll-tabs
  - jekyll-spaceship
  - jekyll-redirect-from

include:
  - idp/static

keep_files:
  - idp/static

defaults:
  - scope:
      path: "idp/resources/"  # The folder where your markdown files reside
      type: "pages"        # Pages that are in this folder
    values:
      parent: Other Resources
  - scope:
      path: "idp/visualizations/"
      type: "pages"
      nav_order: 1
    values:
      parent: Visualizations
  - scope:
      path: "idp/machine-learning/"
      type: "pages"
    values:
      parent: Machine Learning
